services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/sql/db_init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: remindme_app
    depends_on:
      - db
      - asr
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_TABLE: ${DB_TABLE}
      ASR_URL: http://asr:8000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    working_dir: /app

  asr:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/asr/Dockerfile
    ports:
      - "8000:8000"
    environment:
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

volumes:
  postgres_data:
  hf_cache:
